#!/usr/bin/env python3
"""Train the SimpleRNN, export Q8.8 weights to .mem files,
   and generate the Verilog include file for neuron instances."""

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

# ---- reproducibility ----
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

# ---- hyper-parameters (must match RTL) ----
EPOCHS           = 100
BATCH_SIZE       = 16
TRAIN_TEST_SPLIT = 0.8
MIN              = 12
N_HIDDEN         = 128
FILE_NAME        = "book_store_sales.csv"
OUT_DIR          = "mem"
HDR_FILE         = "rnn_inst.vh"

# ---- helpers ----
def readfile(fn):
    with open(fn, 'r', encoding='utf-8') as f:
        next(f)                         # skip header
        return np.array([float(line.split(',')[1]) for line in f],
                        dtype=np.float32)

def float_to_q88(v):
    """Float → Q8.8 as unsigned 16-bit integer."""
    i = int(round(v * 256.0))
    i = max(-32768, min(32767, i))
    return i & 0xFFFF

def save_mem(path, vals):
    with open(path, 'w') as f:
        for v in vals:
            f.write(f"{v:04X}\n")

# ---- read & normalise ----
sales  = readfile(FILE_NAME)
months = len(sales)
split  = int(months * TRAIN_TEST_SPLIT)

train_sales = sales[:split]
test_sales  = sales[split:]

mean   = float(np.mean(train_sales))
stddev = float(np.std(train_sales))

train_std = (train_sales - mean) / stddev
test_std  = (test_sales  - mean) / stddev

# ---- build datasets ----
def make_dataset(series):
    n = len(series)
    X = np.zeros((n - MIN, n - 1, 1), dtype=np.float32)
    y = np.zeros((n - MIN, 1),        dtype=np.float32)
    for i in range(n - MIN):
        X[i, -(i + MIN):, 0] = series[:i + MIN]
        y[i, 0]              = series[i + MIN]
    return X, y

train_X, train_y = make_dataset(train_std)
test_X,  test_y  = make_dataset(test_std)

# ---- build & train ----
model = Sequential([
    SimpleRNN(N_HIDDEN, activation='relu', input_shape=(None, 1)),
    Dense(1, activation='linear')
])
model.compile(loss='mean_squared_error', optimizer='adam',
              metrics=['mean_absolute_error'])
model.fit(train_X, train_y,
          validation_data=(test_X, test_y),
          epochs=EPOCHS, batch_size=BATCH_SIZE,
          verbose=2, shuffle=True)

# ---- extract weights ----
W_x, W_h, b_rnn   = model.layers[0].get_weights()   # (1,128), (128,128), (128,)
W_d, b_dense       = model.layers[1].get_weights()    # (128,1), (1,)

os.makedirs(OUT_DIR, exist_ok=True)

# RNN neuron i: w[0]=bias[i],  w[1]=W_x[0,i],  w[2..129]=W_h[0..127,i]
for i in range(N_HIDDEN):
    vals = [float(b_rnn[i]), float(W_x[0, i])]
    for j in range(N_HIDDEN):
        vals.append(float(W_h[j, i]))
    save_mem(os.path.join(OUT_DIR, f"rnn_w_{i:03d}.mem"),
             [float_to_q88(v) for v in vals])

# Dense neuron: w[0]=bias, w[1..128]=W_d[0..127,0]
vals_d = [float(b_dense[0])]
for j in range(N_HIDDEN):
    vals_d.append(float(W_d[j, 0]))
save_mem(os.path.join(OUT_DIR, "dense_w.mem"),
         [float_to_q88(v) for v in vals_d])

# ---- generate Verilog include (128 parallel RNN neurons) ----
with open(os.path.join(OUT_DIR, HDR_FILE), 'w') as f:
    f.write("// Auto-generated by export_weights.py — do not edit\n")
    for i in range(N_HIDDEN):
        hi = 16 * i + 15
        lo = 16 * i
        f.write(
            f'neuron #(\n'
            f'    .NUM_INPUTS  (129),\n'
            f'    .WEIGHT_FILE ("mem/rnn_w_{i:03d}.mem")\n'
            f') u_rnn_{i:03d} (\n'
            f'    .clk       (clk),\n'
            f'    .rst_n     (rst_n),\n'
            f'    .start     (rnn_start),\n'
            f'    .din       (rnn_din),\n'
            f'    .din_valid (rnn_din_valid),\n'
            f'    .dout      (rnn_dout_flat[{hi}:{lo}]),\n'
            f'    .done      (rnn_done_vec[{i}]),\n'
            f'    .relu_en   (1\'b1)\n'
            f');\n\n'
        )
    f.write("// end auto-generated\n")

# ---- save normalisation constants ----
with open(os.path.join(OUT_DIR, "norm.txt"), 'w') as f:
    f.write(f"{mean}\n{stddev}\n")

print(f"\n[OK] Exported to {OUT_DIR}/")
print(f"     {N_HIDDEN} RNN .mem files  +  1 dense .mem  +  rnn_inst.vh")
print(f"     mean = {mean:.4f},  stddev = {stddev:.4f}")
print(f"     Total BRAMs needed: {N_HIDDEN + 1}")
