#!/usr/bin/env python3
"""Train the RNN, export Q8.8 weights to .mem files,
   and generate the Verilog include file for neuron instances."""

import numpy as np
import os, struct
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

# ---------- hyper-params (must match notebook) ----------
EPOCHS         = 100
BATCH_SIZE     = 16
TRAIN_TEST_SPLIT = 0.8
MIN            = 12
N_HIDDEN       = 128
FILE_NAME      = "book_store_sales.csv"
OUT_DIR        = "mem"          # .mem output directory
HDR_FILE       = "rnn_inst.vh"  # generated Verilog include

# ---------- helpers ----------
def readfile(fn):
    with open(fn, 'r', encoding='utf-8') as f:
        next(f)
        data = [float(line.split(',')[1]) for line in f]
    return np.array(data, dtype=np.float32)

def float_to_q88(v):
    """Convert float to Q8.8 (signed 16-bit), return unsigned 16-bit int."""
    i = int(round(v * 256.0))
    i = max(-32768, min(32767, i))
    return i & 0xFFFF

def save_mem(path, vals):
    """Write a list of Q8.8 uint16 values to a hex .mem file."""
    with open(path, 'w') as f:
        for v in vals:
            f.write(f"{v:04X}\n")

# ---------- read & normalise ----------
sales = readfile(FILE_NAME)
months = len(sales)
split  = int(months * TRAIN_TEST_SPLIT)
train_sales = sales[:split]
test_sales  = sales[split:]

mean   = float(np.mean(train_sales))
stddev = float(np.std(train_sales))

train_std = (train_sales - mean) / stddev
test_std  = (test_sales  - mean) / stddev

# ---------- build dataset ----------
def make_dataset(series):
    n = len(series)
    X = np.zeros((n - MIN, n - 1, 1), dtype=np.float32)
    y = np.zeros((n - MIN, 1),        dtype=np.float32)
    for i in range(n - MIN):
        X[i, -(i + MIN):, 0] = series[:i + MIN]
        y[i, 0]              = series[i + MIN]
    return X, y

train_X, train_y = make_dataset(train_std)
test_X,  test_y  = make_dataset(test_std)

# ---------- build & train ----------
model = Sequential([
    SimpleRNN(N_HIDDEN, activation='relu', input_shape=(None, 1)),
    Dense(1, activation='linear')
])
model.compile(loss='mean_squared_error', optimizer='adam',
              metrics=['mean_absolute_error'])
model.fit(train_X, train_y, validation_data=(test_X, test_y),
          epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=2, shuffle=True)

# ---------- extract weights ----------
rnn_layer   = model.layers[0]
dense_layer = model.layers[1]

W_x, W_h, b_rnn   = rnn_layer.get_weights()   # (1,128), (128,128), (128,)
W_d, b_dense       = dense_layer.get_weights()  # (128,1), (1,)

os.makedirs(OUT_DIR, exist_ok=True)

# RNN neuron i:  w[0]=bias[i], w[1]=W_x[0,i], w[2..129]=W_h[0..127,i]
for i in range(N_HIDDEN):
    vals = [float(b_rnn[i])]
    vals.append(float(W_x[0, i]))
    for j in range(N_HIDDEN):
        vals.append(float(W_h[j, i]))
    mem = [float_to_q88(v) for v in vals]
    save_mem(os.path.join(OUT_DIR, f"rnn_w_{i:03d}.mem"), mem)

# Dense neuron:  w[0]=bias, w[1..128]=W_d[0..127,0]
vals_d = [float(b_dense[0])]
for j in range(N_HIDDEN):
    vals_d.append(float(W_d[j, 0]))
mem_d = [float_to_q88(v) for v in vals_d]
save_mem(os.path.join(OUT_DIR, "dense_w.mem"), mem_d)

# ---------- generate Verilog include ----------
with open(os.path.join(OUT_DIR, HDR_FILE), 'w') as f:
    f.write("// Auto-generated by export_weights.py – do not edit\n")
    for i in range(N_HIDDEN):
        hi = 16 * i + 15
        lo = 16 * i
        f.write(
            f'neuron #(.NUM_INPUTS(129),'
            f' .WEIGHT_FILE("mem/rnn_w_{i:03d}.mem"))'
            f' u_rnn_{i:03d} (\n'
            f'    .clk(clk), .rst_n(rst_n),\n'
            f'    .start(rnn_start), .din(rnn_din),\n'
            f'    .din_valid(rnn_din_valid),\n'
            f'    .dout(rnn_dout_flat[{hi}:{lo}]),\n'
            f'    .done(rnn_done_vec[{i}]),\n'
            f'    .relu_en(1\'b1)\n'
            f');\n'
        )
    f.write("// end auto-generated\n")

# ---------- save normalisation constants ----------
with open(os.path.join(OUT_DIR, "norm.txt"), 'w') as f:
    f.write(f"{mean}\n{stddev}\n")

print(f"[OK] Weights exported to {OUT_DIR}/")
print(f"     mean={mean:.4f}  stddev={stddev:.4f}")
