`timescale 1ns / 1ps
//============================================================================
// MNIST Neural Network Inference Core  (sequential, 784→25→10)
//
// Architecture (from 3-2-mnist_learning_conf5.ipynb):
//   Flatten:  28×28 → 784
//   Hidden:   Dense(25, ReLU)      — 784×25 weights + 25 biases = 19,625
//   Output:   Dense(10, softmax)   — 25×10  weights + 10 biases =    260
//   Total params: 19,885
//
// For inference, softmax is replaced by argmax (monotonic, same result).
//
// Arithmetic: signed 16-bit Q8.8 fixed-point
//   MAC accumulator: signed 32-bit (Q24.8)
//   One multiply-accumulate per clock cycle.
//
// Timing at 50 MHz:
//   Layer 1: 25 neurons × (1 prime + 785 MAC) = 19,650 cycles
//   Layer 2: 10 neurons × (1 prime +  26 MAC) =    270 cycles
//   Argmax + overhead:                              ~30 cycles
//   Total ≈ 19,950 cycles ≈ 0.4 ms per image
//
// Weight / bias / image storage: Block RAM, initialised from .mem files
// generated by the companion export_weights.py script.
//============================================================================

module mnist_nn_core (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,         // pulse high 1 cycle to begin
    input  wire [3:0]  img_sel,       // test image index (0..NUM_IMAGES-1)

    output reg  [3:0]  digit,         // predicted class 0..9
    output reg         done,          // high 1 cycle when result ready
    output reg         busy           // high during inference
);

    // ================================================================
    //  Network parameters
    // ================================================================
    localparam N_IN   = 784;          // 28 × 28 input pixels
    localparam N_HID  = 25;           // hidden-layer neurons
    localparam N_OUT  = 10;           // output classes (digits 0-9)
    localparam N_IMG  = 10;           // test images in ROM

    // ================================================================
    //  Weight, bias, and test-image storage  (Block RAM)
    // ================================================================
    //  Layout — Layer 1 weights:
    //    address = neuron * N_IN + pixel
    //    w1[0..783]     = neuron 0 weights
    //    w1[784..1567]  = neuron 1 weights  ...
    //
    //  Layout — Layer 2 weights:
    //    address = neuron * N_HID + hidden_idx
    //
    //  Layout — Test images:
    //    address = image * N_IN + pixel

    (* ram_style = "block" *) reg signed [15:0] w1      [0:N_IN*N_HID-1];
    (* ram_style = "block" *) reg signed [15:0] w2      [0:N_HID*N_OUT-1];
    (* ram_style = "block" *) reg signed [15:0] img_rom [0:N_IN*N_IMG-1];
    reg signed [15:0] b1 [0:N_HID-1];
    reg signed [15:0] b2 [0:N_OUT-1];

    initial begin
        $readmemh("w1.mem",          w1);
        $readmemh("b1.mem",          b1);
        $readmemh("w2.mem",          w2);
        $readmemh("b2.mem",          b2);
        $readmemh("test_images.mem", img_rom);
    end

    // ================================================================
    //  Synchronous BRAM reads  (1-cycle latency)
    // ================================================================
    reg [14:0] w1_addr;               // 0 .. 19,599
    reg  [7:0] w2_addr;               // 0 .. 249
    reg [12:0] img_addr;              // 0 .. 7,839

    reg signed [15:0] w1_rd, w2_rd, img_rd;

    always @(posedge clk) begin
        w1_rd  <= w1[w1_addr];
        w2_rd  <= w2[w2_addr];
        img_rd <= img_rom[img_addr];
    end

    // ================================================================
    //  Hidden-layer register file  (padded to 32 for safe indexing)
    // ================================================================
    reg signed [15:0] hidden [0:31];

    // ================================================================
    //  FSM states
    // ================================================================
    localparam [2:0]
        S_IDLE     = 3'd0,
        S_L1_PRIME = 3'd1,           // set first BRAM address for L1
        S_L1_MAC   = 3'd2,           // multiply-accumulate for L1
        S_L1_POST  = 3'd3,           // ReLU + store hidden neuron
        S_L2_PRIME = 3'd4,           // set first BRAM address for L2
        S_L2_MAC   = 3'd5,           // multiply-accumulate for L2
        S_L2_POST  = 3'd6,           // argmax update
        S_DONE     = 3'd7;

    reg [2:0]         state;
    reg [4:0]         neuron;         // current neuron index
    reg [9:0]         cnt;            // input counter within MAC loop
    reg signed [31:0] acc;            // MAC accumulator  (Q24.8)
    reg [14:0]        w1_base;        // base addr in w1 for current neuron
    reg  [7:0]        w2_base;        // base addr in w2 for current neuron
    reg [12:0]        img_base;       // base addr in img_rom for selected image

    // Argmax tracking
    reg [3:0]         best_idx;
    reg signed [31:0] best_val;

    // ================================================================
    //  Combinational products
    // ================================================================
    wire signed [31:0] prod_l1 = w1_rd * img_rd;

    //  For L2 the hidden array is indexed by (cnt - 1) because the
    //  BRAM pipeline delays w2_rd by one cycle relative to cnt.
    wire [4:0]         h_idx   = cnt[4:0] - 5'd1;
    wire signed [31:0] prod_l2 = w2_rd * hidden[h_idx];

    // ================================================================
    //  Main FSM
    // ================================================================
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state    <= S_IDLE;
            done     <= 1'b0;
            busy     <= 1'b0;
            digit    <= 4'd0;
            neuron   <= 5'd0;
            cnt      <= 10'd0;
            acc      <= 32'sd0;
            w1_base  <= 15'd0;
            w2_base  <= 8'd0;
            img_base <= 13'd0;
            best_idx <= 4'd0;
            best_val <= 32'sd0;
            w1_addr  <= 15'd0;
            w2_addr  <= 8'd0;
            img_addr <= 13'd0;
        end else begin
            done <= 1'b0;                 // default: pulse

            case (state)

                // ------------------------------------------------
                //  IDLE — wait for start
                // ------------------------------------------------
                S_IDLE: begin
                    busy <= 1'b0;
                    if (start) begin
                        busy     <= 1'b1;
                        neuron   <= 5'd0;
                        w1_base  <= 15'd0;
                        img_base <= img_sel * 13'd784;
                        best_val <= -32'sh7FFF_FFFF;
                        best_idx <= 4'd0;
                        state    <= S_L1_PRIME;
                    end
                end

                // ------------------------------------------------
                //  Layer 1 — PRIME: issue first BRAM addresses
                // ------------------------------------------------
                S_L1_PRIME: begin
                    w1_addr  <= w1_base;
                    img_addr <= img_base;
                    acc      <= {{16{b1[neuron][15]}}, b1[neuron]};
                    cnt      <= 10'd0;
                    state    <= S_L1_MAC;
                end

                // ------------------------------------------------
                //  Layer 1 — MAC loop (784 inputs per neuron)
                //
                //  cnt = 0        : pipeline fill (no accumulate)
                //  cnt = 1 .. 784 : accumulate input (cnt-1)
                //  cnt = 784      : last accumulate → POST
                // ------------------------------------------------
                S_L1_MAC: begin
                    if (cnt > 10'd0)
                        acc <= acc + (prod_l1 >>> 8);

                    if (cnt < (N_IN - 1)) begin
                        w1_addr  <= w1_base + {5'd0, cnt} + 15'd1;
                        img_addr <= img_base + {3'd0, cnt} + 13'd1;
                    end

                    if (cnt == N_IN)
                        state <= S_L1_POST;
                    else
                        cnt <= cnt + 10'd1;
                end

                // ------------------------------------------------
                //  Layer 1 — POST: ReLU + store, advance neuron
                // ------------------------------------------------
                S_L1_POST: begin
                    // ReLU with Q8.8 saturation
                    if (acc[31])                        // negative → 0
                        hidden[neuron] <= 16'd0;
                    else if (|acc[30:15])               // overflow → saturate
                        hidden[neuron] <= 16'h7FFF;
                    else                                // fits in Q8.8
                        hidden[neuron] <= acc[15:0];

                    if (neuron == (N_HID - 1)) begin
                        neuron  <= 5'd0;
                        w2_base <= 8'd0;
                        state   <= S_L2_PRIME;
                    end else begin
                        neuron  <= neuron + 5'd1;
                        w1_base <= w1_base + N_IN;
                        state   <= S_L1_PRIME;
                    end
                end

                // ------------------------------------------------
                //  Layer 2 — PRIME
                // ------------------------------------------------
                S_L2_PRIME: begin
                    w2_addr <= w2_base;
                    acc     <= {{16{b2[neuron[3:0]][15]}}, b2[neuron[3:0]]};
                    cnt     <= 10'd0;
                    state   <= S_L2_MAC;
                end

                // ------------------------------------------------
                //  Layer 2 — MAC loop (25 hidden inputs per neuron)
                // ------------------------------------------------
                S_L2_MAC: begin
                    if (cnt > 10'd0)
                        acc <= acc + (prod_l2 >>> 8);

                    if (cnt < (N_HID - 1))
                        w2_addr <= w2_base + cnt[7:0] + 8'd1;

                    if (cnt == N_HID)
                        state <= S_L2_POST;
                    else
                        cnt <= cnt + 10'd1;
                end

                // ------------------------------------------------
                //  Layer 2 — POST: argmax tracking
                //  (no activation — argmax(softmax(x)) == argmax(x))
                // ------------------------------------------------
                S_L2_POST: begin
                    if (acc > best_val) begin
                        best_val <= acc;
                        best_idx <= neuron[3:0];
                    end

                    if (neuron[3:0] == (N_OUT - 1)) begin
                        state <= S_DONE;
                    end else begin
                        neuron  <= neuron + 5'd1;
                        w2_base <= w2_base + N_HID[7:0];
                        state   <= S_L2_PRIME;
                    end
                end

                // ------------------------------------------------
                //  DONE — latch result
                // ------------------------------------------------
                S_DONE: begin
                    digit <= best_idx;
                    done  <= 1'b1;
                    state <= S_IDLE;
                end

            endcase
        end
    end

endmodule
